name: Test Sending Request

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  send_request:
    name: Send Request to Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Send Post Request
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://iedoc.eng.cmu.ac.th/hooks/redeploy-iedoc"
          method: "GET"
